[project]
name = "mech-terp-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "circuitsvis>=1.43.3",
    "eindex-callum>=0.1.2",
    "einops>=0.8.2",
    "ipykernel>=7.2.0",
    "ipython>=9.13.0",
    "jaxtyping>=0.3.9",
    "jupyter>=1.1.1",
    "numpy>=2.4.4",
    "plotly>=6.7.0",
    "torch>=2.11.0",
    "datasets>=3.0",
    "transformers>=4.56.0,<5",
    "transformer-lens>=3.2.1",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
nvidia-cublas-cu12 = { index = "pytorch-cu128" }
nvidia-cuda-cupti-cu12 = { index = "pytorch-cu128" }
nvidia-cuda-nvrtc-cu12 = { index = "pytorch-cu128" }
nvidia-cuda-runtime-cu12 = { index = "pytorch-cu128" }
nvidia-cudnn-cu12 = { index = "pytorch-cu128" }
nvidia-cufft-cu12 = { index = "pytorch-cu128" }
nvidia-cufile-cu12 = { index = "pytorch-cu128" }
nvidia-curand-cu12 = { index = "pytorch-cu128" }
nvidia-cusolver-cu12 = { index = "pytorch-cu128" }
nvidia-cusparse-cu12 = { index = "pytorch-cu128" }
nvidia-cusparselt-cu12 = { index = "pytorch-cu128" }
nvidia-nccl-cu12 = { index = "pytorch-cu128" }
nvidia-nvjitlink-cu12 = { index = "pytorch-cu128" }
nvidia-nvshmem-cu12 = { index = "pytorch-cu128" }
nvidia-nvtx-cu12 = { index = "pytorch-cu128" }
